### ISSUE TITLE
SQLite database error

### ISSUE THREAD

**Issue by koshrf** [Gsync/jobsync#18]
Tried to do a compose up -d after a git clone of the repository, waited for the build and after few seconds the container goes down.

```sh
npm WARN exec The following package was not found and will be installed: prisma@6.1.0
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "dev.db" at "file:/data/dev.db"

Error: Schema engine error:
SQLite database error
unable to open database file: /data/dev.db

npm notice 
npm notice New major version of npm available! 9.6.4 -> 11.0.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v11.0.0>
npm notice Run `npm install -g npm@11.0.0` to update!
npm notice 
```

Tried to create the database by hand but I'm getting a read-only problem when the application try to reach it.

**Comment by koshrf** [comment]
Temporal fix:

```sh
sudo touch jobsyncdb/data/dev.db
```

And edit the docker-compose.yml to run as root with a user: "0"

The container run normally as nextjs user and was getting read-only problems even when the file had 0666 permissions, didn't want to deal with it atm so just ran the container as root and will change the dockerfile and compose later to accomodate for the missing sqlite3 file.

**Comment by koshrf** [comment]
> Are you running it on a local machine or server? Is it a clean install or overwrite? What OS are you running it on? I will try to replicate the issue, glad that you found a work around.

I did run it on my local machine and in a homelab, both with ubuntu 24.04, I did change the docker-compose a little bit to fit my env

```yaml
services:
  app:
    container_name: jobsync_app
    build:
      context: .
      dockerfile: Dockerfile
    image: jobsync_app_image
    user: "0"
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: file:/data/dev.db
      # Change your initial username and password here
      USER_EMAIL: <my-email>
      USER_PASSWORD: <my-password>
      # Refer to readme to generate auth secret
      #AUTH_SECRET: Cft42eLmgapfLoot7ByiCL9ToNfbqZ4xaaMuOJsbm+9u
      AUTH_SECRET: <my-auth-secret>
      #NEXTAUTH_URL: http://localhost:3000
      #AUTH_TRUST_HOST: http://localhost:3000
      NEXTAUTH_URL: https://jobsync.<local-fqdn>
      AUTH_TRUST_HOST: https://jobsync.<local-fqdn> 
    volumes:
      - ./jobsyncdb/data:/data
    networks:
      - compose_default
networks:
  compose_default:
    external: true
```
